$global:MusicData = @{
    "Israeli_General" = @("galgalatz playlist", "israeli new songs", "best of israeli music"); "Israeli_Rock" = @("90s israeli rock", "best of israeli rock", "eifo hayeled live", "hayehudim live", "mashina greatest hits"); "Israeli_PopRock" = @("shlomo artzi live", "gidi gov best", "danny sanderson hits", "rami kleinstein hits"); "Mizrahi" = @("new mizrahi playlist", "mediterranean hits 2024", "eyal golan best", "sarit hadad live", "eden ben zaken hits"); "Mizrahi_Retro" = @("zohar argov best", "haim moshe hits", "shimi tavori best", "margol hits"); "Mizrahi_Diach" = @("sad israeli songs", "ofer levi best", "tamir gal best", "yossi eden best"); "Old_Israeli" = @("classic israeli songs", "arik einstein best", "shalom hanoch live", "yehoram gaon best"); "Israeli_Kaveret" = @("kaveret best", "gazoz band", "doda band", "danny sanderson best"); "Israeli_HipHop" = @("israeli hip hop", "tuna best", "shekel live", "peled playlist", "hadag nahash live"); "Israeli_Indie" = @("israeli indie music", "noga erez best", "masa umatan playlist", "tomer yeshayahu live"); "Israeli_Alt" = @("mercedes band hits", "full trunk live", "girafot band", "the collective", "lola marsh"); "Israeli_Army" = @("idf bands best", "idf songs", "greatest idf bands"); "Israeli_Kids" = @("classic kids songs", "hakeves ha16", "kids festival songs"); "Israeli_Euro" = @("israel eurovision all songs", "israeli eurovision songs", "izhar cohen abanibi");
    "Classic_Rock" = @("classic rock greatest hits", "70s rock anthems live", "best of led zeppelin", "queen live aid"); "Alternative" = @("90s alternative rock playlist", "best of nirvana", "pearl jam greatest hits", "radiohead live"); "Rock_Indie" = @("arctic monkeys hits", "the strokes hits", "tame impala hits"); "Rock_Britpop" = @("oasis hits", "blur hits", "pulp hits"); "Hard_Rock" = @("hard rock classics", "acdc live", "guns n roses welcome to the jungle live"); "Punk_Rock" = @("punk rock classics playlist", "best of the ramones", "the clash live"); "Pop_Punk" = @("pop punk anthems", "blink 182 hits", "sum 41 hits"); "Rock_Emo" = @("my chemical romance hits", "fall out boy hits", "paramore hits"); "Rock_Post" = @("post rock playlist", "explosions in the sky hits"); "Nu_Metal" = @("nu metal greatest hits", "linkin park hybrid theory", "limp bizkit hits"); "Rock_Industrial" = @("industrial metal hits", "rammstein hits"); "Soft_Rock" = @("soft rock classics", "fleetwood mac rumors"); "Prog_Rock" = @("progressive rock classics", "king crimson live", "yes roundabout live"); "Grunge" = @("90s grunge playlist", "soundgarden live", "alice in chains unplugged"); "Metal_Heavy" = @("heavy metal classics", "best of iron maiden"); "Metal_Thrash" = @("thrash metal playlist", "best of metallica", "slayer raining blood live"); "Metal_Core" = @("metalcore hits", "bring me the horizon hits"); "Metal_Symphonic" = @("symphonic metal hits", "nightwish hits"); "Metal_Folk" = @("folk metal playlist", "eluveitie hits"); "Metal_Hair" = @("hair metal 80s hits", "motley crue hits");
    "Pop_80s" = @("80s music hits playlist", "best of michael jackson"); "Pop_90s" = @("90s pop official video", "britney spears baby one more time"); "Pop_2000s" = @("2000s pop hits", "best of lady gaga"); "Pop_2010s" = @("2010s pop hits", "katy perry hits"); "Pop_Modern" = @("today's top hits official", "best of dua lipa"); "Pop_Indie" = @("indie pop hits", "foster the people hits"); "Pop_Disco" = @("disco hits 70s", "abba greatest hits"); "Pop_Latin" = @("latin pop hits", "shakira hits"); "Pop_BoyBands" = @("best boy bands hits", "backstreet boys hits"); "Pop_GirlGroups" = @("best girl groups hits", "spice girls hits"); "Pop_Eurovision" = @("eurovision greatest hits", "eurovision winners playlist");
    "Elec_House" = @("house music hits", "daft punk hits"); "Elec_DeepHouse" = @("deep house mix", "kygo hits"); "Elec_Techno" = @("techno boiler room set", "charlotte de witte"); "Elec_EDM" = @("edm festival mix", "avicii hits"); "Elec_Trance" = @("uplifting trance mix 2024", "armin van buuren live"); "Elec_Psy" = @("psytrance festival mix", "infected mushroom live"); "Elec_Synthwave" = @("synthwave retrowave mix", "the midnight official videos"); "Elec_Dubstep" = @("classic dubstep mix", "skrillex hits"); "Elec_DnB" = @("drum and bass mix", "pendulum live set"); "Elec_Hardstyle" = @("hardstyle top hits", "headhunterz hits"); "Elec_Ambient" = @("ambient music mix", "brian eno ambient"); "Elec_FutureBass" = @("future bass mix", "flume hits"); "Elec_Lofi" = @("lofi hip hop radio beats to relax");
    "HipHop_Old" = @("80s 90s hip hop classics", "best of tupac"); "HipHop_New" = @("modern hip hop playlist", "kendrick lamar hits"); "HipHop_Trap" = @("trap music hits", "travis scott hits"); "HipHop_JazzRap" = @("jazz rap playlist", "a tribe called quest hits"); "World_Reggae" = @("reggae classics playlist", "best of bob marley"); "World_Latin" = @("reggaeton playlist 2024", "bad bunny live"); "World_KPop" = @("k-pop top hits", "bts official music video"); "World_Afrobeats" = @("afrobeats playlist", "burna boy hits"); "World_Bossa" = @("bossa nova jazz", "antonio carlos jobim"); "World_Celtic" = @("celtic music mix", "irish pub songs"); "World_Balkan" = @("balkan beat box hits");
    "Jazz_Classic" = @("jazz classics playlist", "miles davis kind of blue"); "Jazz_Bebop" = @("bebop jazz mix", "charlie parker hits"); "Jazz_Smooth" = @("smooth jazz mix", "kenny g hits"); "Jazz_Fusion" = @("jazz fusion hits", "herbie hancock hits"); "Blues_Classic" = @("best of blues music", "bb king live"); "Blues_Rock" = @("blues rock hits", "srv texas flood"); "Soul_Classic" = @("best of motown", "james brown get on up"); "Soul_Neo" = @("neo soul mix", "erykah badu hits"); "Country_Classic" = @("classic country hits", "johnny cash folsom prison"); "Country_Modern" = @("modern country hits", "luke combs hits"); "Folk" = @("folk music classics", "bob dylan hits");
    "Classical_Epic" = @("epic classical music", "wagner ride of the valkyries"); "Classical_Relax" = @("relaxing classical music", "debussy clair de lune"); "OST_Movies" = @("hans zimmer live", "lord of the rings music"); "OST_Disney" = @("disney hits playlist", "lion king soundtrack"); "OST_Gaming" = @("best video game music", "skyrim soundtrack"); "OST_Anime" = @("best anime openings", "ghibli soundtrack"); "OST_Musicals" = @("broadway greatest hits", "hamilton soundtrack");
    "Artist_Queen" = @("queen greatest hits"); "Artist_Beatles" = @("the beatles greatest hits"); "Artist_Weeknd" = @("the weeknd greatest hits"); "Artist_Taylor" = @("taylor swift greatest hits"); "Artist_Eminem" = @("eminem greatest hits"); "Artist_Coldplay" = @("coldplay greatest hits"); "Artist_Beyonce" = @("beyonce greatest hits"); "Artist_Rihanna" = @("rihanna greatest hits"); "Artist_JustinB" = @("justin bieber greatest hits"); "Artist_EdSheeran" = @("ed sheeran greatest hits"); "Artist_Bruno" = @("bruno mars greatest hits"); "Artist_Adele" = @("adele greatest hits"); "Artist_Ariana" = @("ariana grande greatest hits"); "Artist_DuaLipa" = @("dua lipa greatest hits"); "Artist_Drake" = @("drake greatest hits"); "Artist_Kendrick" = @("kendrick lamar greatest hits"); "Artist_Gaga" = @("lady gaga greatest hits"); "Artist_Katy" = @("katy perry greatest hits"); "Artist_Imagine" = @("imagine dragons greatest hits"); "Artist_Maroon5" = @("maroon 5 greatest hits"); "Artist_MJ" = @("michael jackson greatest hits"); "Artist_Elvis" = @("elvis presley greatest hits"); "Artist_Bowie" = @("david bowie greatest hits"); "Artist_Elton" = @("elton john greatest hits"); "Artist_PinkFloyd" = @("pink floyd greatest hits"); "Artist_LedZep" = @("led zeppelin greatest hits"); "Artist_Linkin" = @("linkin park greatest hits"); "Artist_Harry" = @("harry styles greatest hits"); "Artist_Billie" = @("billie eilish greatest hits"); "Artist_Miley" = @("miley cyrus greatest hits"); "Artist_Avicii" = @("avicii greatest hits"); "Artist_Nirvana" = @("nirvana greatest hits");
    "Artist_Omer" = @("omer adam all songs"); "Artist_Shlomo" = @("shlomo artzi all songs"); "Artist_Arik" = @("arik einstein all songs"); "Artist_Tuna" = @("tuna best"); "Artist_Ravid" = @("ravid plotnik best"); "Artist_EdenH" = @("eden hason best"); "Artist_Osher" = @("osher cohen best"); "Artist_Hanan" = @("hanan ben ari best"); "Artist_Noa" = @("noa kirel best"); "Artist_Eyal" = @("eyal golan best"); "Artist_Sarit" = @("sarit hadad best"); "Artist_Peer" = @("peer tasi best"); "Artist_Yasmin" = @("yasmin moallem best"); "Artist_Idan" = @("idan raichel best"); "Artist_Aviv" = @("aviv geffen best"); "Artist_Ivri" = @("ivri lider best"); "Artist_Static" = @("static best"); "Artist_Shalom" = @("shalom hanoch best"); "Artist_Yehudit" = @("yehudit ravitz best"); "Artist_Ethnix" = @("ethnix best"); "Artist_Yehudim" = @("hayehudim best"); "Artist_EdenBZ" = @("eden ben zaken best"); "Artist_Ishay" = @("ishay ribo best"); "Artist_Nathan" = @("nathan goshen best"); "Artist_Miri" = @("miri mesika best"); "Artist_Moshe" = @("moshe peretz best"); "Artist_Hadag" = @("hadag nahash best"); "Artist_Sub" = @("subliminal best");
    "Mood_Workout" = @("gym workout music mix"); "Mood_Party" = @("party music playlist"); "Mood_Focus" = @("ambient music for focus"); "Mood_Coffee" = @("coffee shop jazz"); "Mood_Rain" = @("jazz and rain sounds"); "Mood_Nature" = @("forest sounds for relaxing"); "Mood_Gaming" = @("epic gaming music mix")
}

function Play-Music {
    param([string[]]$Terms, [string]$CategoryName)
    $statusTxt = Get-GuiElement "txtStatusAdv"; if ($statusTxt) { $statusTxt.Text = "Searching YouTube for '$CategoryName' mix..." }
    $statusTxtSimple = Get-GuiElement "txtStatusSimple"; if ($statusTxtSimple) { $statusTxtSimple.Text = "Playing: $CategoryName" }
    [System.Windows.Forms.Application]::DoEvents()
    $randomSearchTerm = Get-Random -InputObject $Terms
    try {
        $encodedSearchTerm = [System.Net.WebUtility]::UrlEncode($randomSearchTerm)
        $searchUrl = "https://www.youtube.com/results?search_query=$encodedSearchTerm"
        $response = Invoke-WebRequest -Uri $searchUrl -UseBasicParsing -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" -TimeoutSec 5
        $pattern = 'watch\?v=([a-zA-Z0-9_-]{11})'; $allMatches = [regex]::Matches($response.Content, $pattern)
        if ($allMatches.Count -gt 0) { $videoIds = $allMatches | ForEach-Object { $_.Groups[1].Value } | Select-Object -Unique; $videoId = $videoIds | Get-Random; $mixUrl = "https://www.youtube.com/watch?v=$videoId"; Start-Process $mixUrl } else { Start-Process $searchUrl }
    }
    catch { $encodedFallback = [System.Net.WebUtility]::UrlEncode($randomSearchTerm); Start-Process "https://www.youtube.com/results?search_query=$encodedFallback" }
}
function Bind-Btn { param($btnName, $dataKey, $displayName) $btn = Get-GuiElement $btnName; if ($btn) { $terms = $global:MusicData[$dataKey]; $btn.Add_Click({ Play-Music -Terms $terms -CategoryName $displayName }.GetNewClosure()) } }

# MUSIC PANEL LOGIC
# Populate Combo for Simple Mode
$cmbMusic = Get-GuiElement "cmbMusicGenre"
foreach ($k in $global:MusicData.Keys) { [void]$cmbMusic.Items.Add($k) }
$cmbMusic.SelectedIndex = 0

# Play Button Simple
Set-Click "btnPlayMusic" {
    $genre = $cmbMusic.SelectedItem
    $terms = $global:MusicData[$genre]
    Play-Music -Terms $terms -CategoryName $genre
}

# Navigation Handlers
Set-Click "btnGoToAdvanced" { (Get-GuiElement "pnlMusicSimple").Visibility = "Collapsed"; (Get-GuiElement "pnlMusicAdvanced").Visibility = "Visible"; (Get-GuiElement "btnGoToAdvanced").Visibility = "Collapsed"; (Get-GuiElement "btnBackToSimple").Visibility = "Visible" }
Set-Click "btnBackToSimple" { (Get-GuiElement "pnlMusicAdvanced").Visibility = "Collapsed"; (Get-GuiElement "pnlMusicSimple").Visibility = "Visible"; (Get-GuiElement "btnBackToSimple").Visibility = "Collapsed"; (Get-GuiElement "btnGoToAdvanced").Visibility = "Visible" }

# BIND ALL MUSIC BUTTONS
Bind-Btn "btnIsrGeneral" "Israeli_General" "Israeli General"; Bind-Btn "btnIsrRock" "Israeli_Rock" "Israeli Rock"; Bind-Btn "btnIsrPopRock" "Israeli_PopRock" "Israeli Pop/Rock"; Bind-Btn "btnMizrahi" "Mizrahi" "Mizrahi New"; Bind-Btn "btnMizrahiRetro" "Mizrahi_Retro" "Mizrahi Retro"; Bind-Btn "btnMizrahiDiach" "Mizrahi_Diach" "Mizrahi Sad"; Bind-Btn "btnOldIsraeli" "Old_Israeli" "Old Classics"; Bind-Btn "btnKaveret" "Israeli_Kaveret" "Kaveret & Co"; Bind-Btn "btnIsrHipHop" "Israeli_HipHop" "Israeli Hip Hop"; Bind-Btn "btnIsrIndie" "Israeli_Indie" "Israeli Indie"; Bind-Btn "btnIsrAlt" "Israeli_Alt" "Israeli Alternative"; Bind-Btn "btnArmy" "Israeli_Army" "Army Bands"; Bind-Btn "btnIsrKids" "Israeli_Kids" "Israeli Kids"; Bind-Btn "btnIsrEuro" "Israeli_Euro" "Israeli Eurovision"
Bind-Btn "btnClassicRock" "Classic_Rock" "Classic Rock"; Bind-Btn "btnAltRock" "Alternative" "Alternative Rock"; Bind-Btn "btnIndieRock" "Rock_Indie" "Indie Rock"; Bind-Btn "btnBritpop" "Rock_Britpop" "Britpop"; Bind-Btn "btnHardRock" "Hard_Rock" "Hard Rock"; Bind-Btn "btnPunk" "Punk_Rock" "Punk Rock"; Bind-Btn "btnPopPunk" "Pop_Punk" "Pop Punk"; Bind-Btn "btnEmo" "Rock_Emo" "Emo Rock"; Bind-Btn "btnPostRock" "Rock_Post" "Post Rock"; Bind-Btn "btnNuMetal" "Nu_Metal" "Nu-Metal"; Bind-Btn "btnIndustrial" "Rock_Industrial" "Industrial Metal"; Bind-Btn "btnSoftRock" "Soft_Rock" "Soft Rock"; Bind-Btn "btnProg" "Prog_Rock" "Progressive Rock"; Bind-Btn "btnGrunge" "Grunge" "Grunge"; Bind-Btn "btnHeavyMetal" "Metal_Heavy" "Heavy Metal"; Bind-Btn "btnThrashMetal" "Metal_Thrash" "Thrash Metal"; Bind-Btn "btnMetalCore" "Metal_Core" "Metalcore"; Bind-Btn "btnSymphonic" "Metal_Symphonic" "Symphonic Metal"; Bind-Btn "btnFolkMetal" "Metal_Folk" "Folk Metal"; Bind-Btn "btnHairMetal" "Metal_Hair" "Hair Metal"
Bind-Btn "btnPop80s" "Pop_80s" "80s Pop"; Bind-Btn "btnPop90s" "Pop_90s" "90s Pop"; Bind-Btn "btnPop2000s" "Pop_2000s" "2000s Pop"; Bind-Btn "btnPop2010s" "Pop_2010s" "2010s Pop"; Bind-Btn "btnPopModern" "Pop_Modern" "Modern Pop"; Bind-Btn "btnIndiePop" "Pop_Indie" "Indie Pop"; Bind-Btn "btnDisco" "Pop_Disco" "Disco 70s"; Bind-Btn "btnLatinPop" "Pop_Latin" "Latin Pop"; Bind-Btn "btnBoyBands" "Pop_BoyBands" "Boy Bands"; Bind-Btn "btnGirlGroups" "Pop_GirlGroups" "Girl Groups"; Bind-Btn "btnEurovision" "Pop_Eurovision" "Eurovision"
Bind-Btn "btnJazz" "Jazz_Classic" "Jazz Classics"; Bind-Btn "btnBebop" "Jazz_Bebop" "Bebop Jazz"; Bind-Btn "btnSmooth" "Jazz_Smooth" "Smooth Jazz"; Bind-Btn "btnFusion" "Jazz_Fusion" "Jazz Fusion"; Bind-Btn "btnBlues" "Blues_Classic" "Blues Legends"; Bind-Btn "btnBluesRock" "Blues_Rock" "Blues Rock"; Bind-Btn "btnSoul" "Soul_Classic" "Classic Soul"; Bind-Btn "btnNeoSoul" "Soul_Neo" "Neo Soul"; Bind-Btn "btnCountry" "Country_Classic" "Classic Country"; Bind-Btn "btnCountryMod" "Country_Modern" "Modern Country"; Bind-Btn "btnFolk" "Folk" "Folk"
Bind-Btn "btnClassicalEpic" "Classical_Epic" "Classical Epic"; Bind-Btn "btnClassicalRelax" "Classical_Relax" "Classical Relax"; Bind-Btn "btnOST" "OST_Movies" "Movie Soundtracks"; Bind-Btn "btnDisney" "OST_Disney" "Disney Hits"; Bind-Btn "btnGaming" "OST_Gaming" "Gaming Music"; Bind-Btn "btnAnime" "OST_Anime" "Anime OST"; Bind-Btn "btnMusicals" "OST_Musicals" "Musicals"; Bind-Btn "btnPiano" "Mood_Piano" "Relaxing Piano"
Bind-Btn "btnHouse" "Elec_House" "House Classic"; Bind-Btn "btnDeepHouse" "Elec_DeepHouse" "Deep House"; Bind-Btn "btnTechno" "Elec_Techno" "Techno"; Bind-Btn "btnEDM" "Elec_EDM" "Mainstream EDM"; Bind-Btn "btnTrance" "Elec_Trance" "Trance"; Bind-Btn "btnPsy" "Elec_Psy" "Psy-Trance"; Bind-Btn "btnSynth" "Elec_Synthwave" "Synthwave"; Bind-Btn "btnDubstep" "Elec_Dubstep" "Dubstep"; Bind-Btn "btnHardstyle" "Elec_Hardstyle" "Hardstyle"; Bind-Btn "btnDnB" "Elec_DnB" "DnB & Jungle"; Bind-Btn "btnAmbient" "Elec_Ambient" "Ambient"; Bind-Btn "btnFutureBass" "Elec_FutureBass" "Future Bass"; Bind-Btn "btnLofi" "Elec_Lofi" "Lofi & Chill"
Bind-Btn "btnOldHipHop" "HipHop_Old" "Old School HipHop"; Bind-Btn "btnNewHipHop" "HipHop_New" "Modern HipHop"; Bind-Btn "btnTrap" "HipHop_Trap" "Trap Music"; Bind-Btn "btnJazzRap" "HipHop_JazzRap" "Jazz Rap"; Bind-Btn "btnReggae" "World_Reggae" "Reggae"; Bind-Btn "btnLatin" "World_Latin" "Reggaeton"; Bind-Btn "btnKpop" "World_KPop" "K-Pop"; Bind-Btn "btnAfro" "World_Afrobeats" "Afrobeats"; Bind-Btn "btnBossa" "World_Bossa" "Bossa Nova"; Bind-Btn "btnCeltic" "World_Celtic" "Celtic"; Bind-Btn "btnBalkan" "World_Balkan" "Balkan"
Bind-Btn "btnQueen" "Artist_Queen" "Queen"; Bind-Btn "btnBeatles" "Artist_Beatles" "The Beatles"; Bind-Btn "btnWeeknd" "Artist_Weeknd" "The Weeknd"; Bind-Btn "btnTaylor" "Artist_Taylor" "Taylor Swift"; Bind-Btn "btnEminem" "Artist_Eminem" "Eminem"; Bind-Btn "btnColdplay" "Artist_Coldplay" "Coldplay"; Bind-Btn "btnBeyonce" "Artist_Beyonce" "Beyonce"; Bind-Btn "btnRihanna" "Artist_Rihanna" "Rihanna"; Bind-Btn "btnJustinB" "Artist_JustinB" "Justin Bieber"; Bind-Btn "btnEdSheeran" "Artist_EdSheeran" "Ed Sheeran"; Bind-Btn "btnBruno" "Artist_Bruno" "Bruno Mars"; Bind-Btn "btnAdele" "Artist_Adele" "Adele"; Bind-Btn "btnAriana" "Artist_Ariana" "Ariana Grande"; Bind-Btn "btnDuaLipa" "Artist_DuaLipa" "Dua Lipa"; Bind-Btn "btnDrake" "Artist_Drake" "Drake"; Bind-Btn "btnKendrick" "Artist_Kendrick" "Kendrick Lamar"; Bind-Btn "btnGaga" "Artist_Gaga" "Lady Gaga"; Bind-Btn "btnKaty" "Artist_Katy" "Katy Perry"; Bind-Btn "btnImagine" "Artist_Imagine" "Imagine Dragons"; Bind-Btn "btnMaroon5" "Artist_Maroon5" "Maroon 5"; Bind-Btn "btnMJ" "Artist_MJ" "Michael Jackson"; Bind-Btn "btnElvis" "Artist_Elvis" "Elvis Presley"; Bind-Btn "btnBowie" "Artist_Bowie" "David Bowie"; Bind-Btn "btnElton" "Artist_Elton" "Elton John"; Bind-Btn "btnPinkFloyd" "Artist_PinkFloyd" "Pink Floyd"; Bind-Btn "btnLedZep" "Artist_LedZep" "Led Zeppelin"; Bind-Btn "btnLinkin" "Artist_Linkin" "Linkin Park"; Bind-Btn "btnHarry" "Artist_Harry" "Harry Styles"; Bind-Btn "btnBillie" "Artist_Billie" "Billie Eilish"; Bind-Btn "btnMiley" "Artist_Miley" "Miley Cyrus"; Bind-Btn "btnAvicii" "Artist_Avicii" "Avicii"; Bind-Btn "btnNirvana" "Artist_Nirvana" "Nirvana"
Bind-Btn "btnOmer" "Artist_Omer" "Omer Adam"; Bind-Btn "btnShlomo" "Artist_Shlomo" "Shlomo Artzi"; Bind-Btn "btnArik" "Artist_Arik" "Arik Einstein"; Bind-Btn "btnTuna" "Artist_Tuna" "Tuna"; Bind-Btn "btnRavid" "Artist_Ravid" "Ravid Plotnik"; Bind-Btn "btnEdenH" "Artist_EdenH" "Eden Hason"; Bind-Btn "btnOsher" "Artist_Osher" "Osher Cohen"; Bind-Btn "btnHanan" "Artist_Hanan" "Hanan Ben Ari"; Bind-Btn "btnNoa" "Artist_Noa" "Noa Kirel"; Bind-Btn "btnEyal" "Artist_Eyal" "Eyal Golan"; Bind-Btn "btnSarit" "Artist_Sarit" "Sarit Hadad"; Bind-Btn "btnPeer" "Artist_Peer" "Peer Tasi"; Bind-Btn "btnYasmin" "Artist_Yasmin" "Yasmin Moallem"; Bind-Btn "btnIdan" "Artist_Idan" "Idan Raichel"; Bind-Btn "btnAviv" "Artist_Aviv" "Aviv Geffen"; Bind-Btn "btnIvri" "Artist_Ivri" "Ivri Lider"; Bind-Btn "btnStatic" "Artist_Static" "Static"; Bind-Btn "btnShalom" "Artist_Shalom" "Shalom Hanoch"; Bind-Btn "btnYehudit" "Artist_Yehudit" "Yehudit Ravitz"; Bind-Btn "btnEthnix" "Artist_Ethnix" "Ethnix"; Bind-Btn "btnYehudim" "Artist_Yehudim" "HaYehudim"; Bind-Btn "btnEdenBZ" "Artist_EdenBZ" "Eden Ben Zaken"; Bind-Btn "btnIshay" "Artist_Ishay" "Ishay Ribo"; Bind-Btn "btnNathan" "Artist_Nathan" "Nathan Goshen"; Bind-Btn "btnMiri" "Artist_Miri" "Miri Mesika"; Bind-Btn "btnMoshe" "Artist_Moshe" "Moshe Peretz"; Bind-Btn "btnHadag" "Artist_Hadag" "HaDag Nahash"; Bind-Btn "btnSub" "Artist_Sub" "Subliminal"
Bind-Btn "btnWorkout" "Mood_Workout" "Workout Mode"; Bind-Btn "btnParty" "Mood_Party" "Party Mode"; Bind-Btn "btnFocus" "Mood_Focus" "Focus Mode"; Bind-Btn "btnCoffee" "Mood_Coffee" "Coffee Shop Mode"; Bind-Btn "btnRain" "Mood_Rain" "Rain Sounds"; Bind-Btn "btnNature" "Mood_Nature" "Nature Sounds"; Bind-Btn "btnGamingMood" "Mood_Gaming" "Gaming Mood"
(Get-GuiElement "btnSurprise").Add_Click({ $allTerms = @(); foreach ($key in $global:MusicData.Keys) { $allTerms += $global:MusicData[$key] }; Play-Music -Terms $allTerms -CategoryName "SURPRISE ME!" })

# Logic for URL-based playlists is removed to favor the search-based system which has more data.
